### ISSUE TITLE
Not detecting all cases

### ISSUE THREAD

**Issue by mathe42** [UltiRequiem/leap-year#7]
```
(await import('https://deno.land/x/leap_year/mod.ts')).isLeapYear('01-01-2000') // returns false
```
should be true.

The problem is the `??` operator! The code on the left has to be nullish not falsey to be evaluated! Should be replaced by `||`

**Comment by UltiRequiem** [comment]
Hey, thanks! I updated the tests.

Sorry for this 😔 

https://github.com/UltiRequiem/leap-year/blob/main/mod_test.ts

A review would be appreciated 🚀 

Will try to do #5 so we get more tests.

**Comment by UltiRequiem** [comment]
We have 100% code coverage now!

**Comment by mathe42** [comment]
You could Count the leapyears from x to x+399 that has to be 97.

But all LGTM I didnt use this could just serfing around deno.land/x ...

**Comment by UltiRequiem** [comment]
Thanks, just created the cli tool(#4 ) so all the issues are closed
